// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xV-AMDu6cXaNfR2-P6yHMhoedEybXDU',
    appId: '1:777664211507:web:0738bc7f24761ee7451146',
    messagingSenderId: '777664211507',
    projectId: 'antello',
    authDomain: 'antello.firebaseapp.com',
    storageBucket: 'antello.appspot.com',
    measurementId: 'G-9R8EY68Y3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5gK-NrE4feneQgttw9ynTF9hnpFvlDA',
    appId: '1:777664211507:android:64a00b97c44cef71451146',
    messagingSenderId: '777664211507',
    projectId: 'antello',
    storageBucket: 'antello.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJFr9O7etqkBqQdAxiMpMrnjPFiZbVlfo',
    appId: '1:777664211507:ios:e5ba10946de8c39a451146',
    messagingSenderId: '777664211507',
    projectId: 'antello',
    storageBucket: 'antello.appspot.com',
    iosClientId: '777664211507-p3ak8d87ald97d6s8hqnjjlv4k9jobcs.apps.googleusercontent.com',
    iosBundleId: 'com.antello',
  );
}
